title: Testing
author: Jill McGlinchey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  12345

# social links
twitter_username: your-twitter-handle
github_username:  jillmcglinchey

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
